name: 'Express Deployment AWS'
description: 'Automatically deploy an Express app to API Gateway/Lambda'

inputs:
  s3-bucket:
    description: 's3 bucket to store builds'
    required: true

  # Region may be removable. Provided by aws-actions/configure-aws-credentials@v1?
  region:
    description: 'Region to deploy to'
    required: true
    default: 'us-east-1'
  stack-name:
    description: 'Cloud Formation stack name'
    required: true

outputs:
  api-url:
    description: 'URL of the API'
    value: ${{ steps.get-url.outputs.api-url }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Compile backend
      run: webpack-cli
      shell: bash

    - name: Upload compilation
      run: aws s3 sync ./dist s3://${{ inputs.s3-bucket }}
      shell: bash

    - run: echo 'uploaded to bucket!'
      shell: bash

    - id: get-url
      run: echo "::set-output name=api-url::$(echo example.com)"
      shell: bash
